### ISSUE TITLE
Unable to Build SIBR_viewers

### ISSUE THREAD

**Issue by Gaaaavin** [graphdeco-inria/hierarchical-3d-gaussians#36]
I followed the instructions in the read me to build SIBR viewers but failed. I got the following error when building:
```
/usr/bin/ld: cannot find -lembree
collect2: error: ld returned 1 exit status
make[2]: *** [src/core/raycaster/CMakeFiles/sibr_raycaster.dir/build.make:247: src/core/raycaster/libsibr_raycaster.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1077: src/core/raycaster/CMakeFiles/sibr_raycaster.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
Note that I have installed embree via `sudo apt install libembree-dev` as instructed in the readme.
I'm on a ubuntu 20.04 machine.

**Comment by arvrschool** [comment]
I have the same problem

**Comment by arvrschool** [comment]
I have fixed the problem by change this:
SIBR_viewers/src/core/raycaster/CMakeLists.txt line 34
`embree` to `embree3`

I hope it's helpful to you.

**Comment by qi-an-zl** [comment]
> I have fixed the problem by change this: SIBR_viewers/src/core/raycaster/CMakeLists.txt line 34 `embree` to `embree3`
> 
> I hope it's helpful to you.

I have tried it, but the problem still exists. Can you give me more detailed steps? Thank you very much

**Comment by Gaaaavin** [comment]
> I have fixed the problem by change this: SIBR_viewers/src/core/raycaster/CMakeLists.txt line 34 `embree` to `embree3`
> 
> I hope it's helpful to you.

@qi-an-zl The solution works for me. Please try delete the whole build file then config and build it again.
